[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  version = "0.9.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
